### ISSUE TITLE
是不是不让用了

### ISSUE THREAD

**Issue by lancer-wang** [AnkiKong/picacomic#10]
请求返回success不附带date了
![image](https://user-images.githubusercontent.com/69783837/116658700-f4c17200-a9c2-11eb-949a-0f5fa8f67b7e.png)

**Comment by AnkiKong** [comment]
贴代码

**Comment by lancer-wang** [comment]
登录可以登录,能获取token,但是其他的所有操作都返回的success
![image](https://user-images.githubusercontent.com/69783837/117227547-a5a79100-ae49-11eb-8d20-f409c763836b.png)

**Comment by AnkiKong** [comment]
你代码没贴全，我也只能猜了。nonce直接定值`b1ab87b4800d4d4590a11701b8551afa`，path要以`/`开头，且url = xxx + path中，xxx结尾的`/`要去掉

**Comment by lancer-wang** [comment]
> 你代码没贴全，我也只能猜了。nonce直接定值`b1ab87b4800d4d4590a11701b8551afa`，path要以`/`开头，且url = xxx + path中，xxx结尾的`/`要去掉
不好意思,没带上path 的代码
实测path以"/"开头之后,登录接口报错,
搜索功能可以使用,但是依然不返回data,
![image](https://user-images.githubusercontent.com/69783837/117242715-5e7cc880-ae68-11eb-947f-0f596831ba4f.png)

**Comment by AnkiKong** [comment]
![image](https://user-images.githubusercontent.com/24975752/117242847-a7cd1800-ae68-11eb-8e93-00baa3d915a5.png)
nonce直接定值`b1ab87b4800d4d4590a11701b8551afa`，我记得反编译出来就是这个定值来着

**Comment by lancer-wang** [comment]
补充运行结果,能获取到token
![image](https://user-images.githubusercontent.com/69783837/117243042-00041a00-ae69-11eb-9b24-c5a90051190c.png)

**Comment by lancer-wang** [comment]
> ![image](https://user-images.githubusercontent.com/24975752/117242847-a7cd1800-ae68-11eb-8e93-00baa3d915a5.png)
> nonce直接定值`b1ab87b4800d4d4590a11701b8551afa`，我记得反编译出来就是这个定值来着

![Uploading image.png…]()

**Comment by lancer-wang** [comment]
![image](https://user-images.githubusercontent.com/69783837/117243118-288c1400-ae69-11eb-95d5-c19f3f141363.png)

**Comment by lancer-wang** [comment]
签到是可以的,而且path没加"/"
![image](https://user-images.githubusercontent.com/69783837/117244930-7d7d5980-ae6c-11eb-8146-067b836bf951.png)

**Comment by lancer-wang** [comment]
我是傻逼,没带token
