### ISSUE TITLE
请问除了Header中的Content - Type还有什么会导致"too many requests"的发生

### ISSUE THREAD

**Issue by NekoRectifier** [AnkiKong/picacomic#11]
以下为生成header的代码:

![image](https://user-images.githubusercontent.com/51020139/121680924-b7d1ba80-caec-11eb-9f49-9f883c25d8c7.png)

![image](https://user-images.githubusercontent.com/51020139/121680108-bbb10d00-caeb-11eb-805a-af207d6994df.png)

麻烦各位大佬看一下

**Comment by AnkiKong** [comment]
header中time和signature的time是要一致的

**Comment by NekoRectifier** [comment]
> header中time和signature的time是要一致的

![image](https://user-images.githubusercontent.com/51020139/121699827-ddb58a00-cb01-11eb-9e6c-54d1db04dd4d.png)

重新调整了时间戳 不过too many request的问题依然存在

**Comment by NekoRectifier** [comment]
手动构建了请求 发现body里面的Content - type优先于time/signature被验证

问题应该还是出在这里
![image](https://user-images.githubusercontent.com/51020139/121762514-f6a55600-cb68-11eb-9fdd-61430dd7c99a.png)

**Comment by NekoRectifier** [comment]
![image](https://user-images.githubusercontent.com/51020139/121762860-2ce3d500-cb6b-11eb-855d-307c33e82717.png)

还是这里的问题 `application/json; charset=UTF-8` 空格,"UTF"大写都要有

不过收到的respond是200但是没得data字段
