### ISSUE TITLE
大佬能更新一下api吗？

### ISSUE THREAD

**Issue by weirdseed** [AnkiKong/picacomic#12]
报错：
发生异常: KeyError
'data'
  File "D:\learning\bika\picacomic-master\pica\pic2.py", line 130, in login
    self.header["authorization"] = json.loads(__a)["data"]["token"]
  File "D:\learning\bika\picacomic-master\pica\pic2.py", line 72, in check
    token = self.login()
  File "D:\learning\bika\picacomic-master\pica\pic2.py", line 57, in __init__
    self.check()
login返回的值：
{
  "code": 400,
  "error": "發現重大版本更新",
  "message": "--",
  "detail": "由於服務器君的問題，因此要強制更新一次。\n\n下載連結：\nhttps://download.wikawika.xyz/apps/2.2.1.2.3.3.apk\nhttp://www.cnpicacomic.com\nhttps://www.picacomic.com"
}

**Comment by NekoRectifier** [comment]
非api问题

**Comment by weirdseed** [comment]
> 非api问题
> pic2.py构建的request报头中的"app_build_version"应在44以上
> ![image](https://user-images.githubusercontent.com/51020139/122767895-aef39c80-d2d5-11eb-8eb4-3519c11b4423.png)
> 
> 改一下的话服务器就不会返回这样的错误了

ok，解决了

**Comment by weirdseed** [comment]
请问如果自己用这些api做一个app自己用应该不会被哔咔查水表吧？

**Comment by NekoRectifier** [comment]
并不清楚哔咔的背景 不过以小范围,非盈利性使用的话应该是不会的

另外如果成功的话可以发一下源码吗? 我做的时候卡在了服务器返回空数据上,一直没有解决

**Comment by weirdseed** [comment]
> 并不清楚哔咔的背景 不过以小范围,非盈利性使用的话应该是不会的
> 
> 另外如果成功的话可以发一下源码吗? 我做的时候卡在了服务器返回空数据上,一直没有解决

我先尝试做吧，不一定做得出来，不过我打算参考https://github.com/AnkiKong/picacomic这个项目来做

**Comment by AnkiKong** [comment]
> > 并不清楚哔咔的背景 不过以小范围,非盈利性使用的话应该是不会的
> > 另外如果成功的话可以发一下源码吗? 我做的时候卡在了服务器返回空数据上,一直没有解决
> 
> 我先尝试做吧，不一定做得出来，不过我打算参考[https://github.com/AnkiKong/picacomic这个项目来做](https://github.com/AnkiKong/picacomic%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E6%9D%A5%E5%81%9A)

https://github.com/AnkiKong/gopica/blob/master/pkg/session/session.go

**Comment by AnkiKong** [comment]
> 并不清楚哔咔的背景 不过以小范围,非盈利性使用的话应该是不会的
> 
> 另外如果成功的话可以发一下源码吗? 我做的时候卡在了服务器返回空数据上,一直没有解决

https://github.com/AnkiKong/gopica/blob/master/pkg/session/session.go

**Comment by NekoRectifier** [comment]
发现是signature的加密出了问题

![image](https://user-images.githubusercontent.com/51020139/122940123-c64e8a80-d3a6-11eb-8427-b162a1b24303.png)

应使用如上代码

服务器返回的response就有data字段了
