### ISSUE TITLE
请求用户数据时返回异常错误信息

### ISSUE THREAD

**Issue by NekoRectifier** [AnkiKong/picacomic#13]
![image](https://user-images.githubusercontent.com/51020139/123104478-8ef4e200-d469-11eb-863a-c543288378f9.png)

如图方式发送请求时得到服务器的返回数据是
`{
      "code": 400,
      "error": "必須更新！",
      "message": "--",
      "detail": "\n你必須更新才能繼續使用嗶咔漫畫。\n請到官網下載最新更新，\n官網： https://www.picacomic.com\n\n如果不能打開官網請透過以下連結直接下載\nhttps://download.wikawika.xyz/apps/2.2.0.0.1.1.apk\n      "
    }`

而无论是改动`app-build-version`还是`app-version`都无法去除该错误信息

另外根据官网数据得
![image](https://user-images.githubusercontent.com/51020139/123104850-e2673000-d469-11eb-813a-d69bb7f677a0.png)
最新版本是`2.2.1.3.3.4` 并非返回值中的`2.2.0.0.1.1`

**Comment by AnkiKong** [comment]
https://github.com/AnkiKong/gopica/blob/master/pkg/picaapi/request.go#L46
按照这里改headers

**Comment by NekoRectifier** [comment]
虽然没写过go 试着读了一下

**Comment by NekoRectifier** [comment]
看了request.go 和 session.go 关于header构建的内容 
![image](https://user-images.githubusercontent.com/51020139/123232759-0bd89800-d50c-11eb-8e85-4edfd3f7a244.png)
![image](https://user-images.githubusercontent.com/51020139/123232824-1c890e00-d50c-11eb-9233-874a470f33fe.png)
并且做了修改
![image](https://user-images.githubusercontent.com/51020139/123233069-55c17e00-d50c-11eb-9fcf-3121ade2c7c9.png)

但是依然出错, 错误信息换成了`unauthorized`

另外,出现
`{ "code": 400, "error": "必須更新！", "message": "--", "detail": "\n你必須更新才能繼續使用嗶咔漫畫。\n請到官網下載最新更新，\n官網： https://www.picacomic.com\n\n如果不能打開官網請透過以下連結直接下載\nhttps://download.wikawika.xyz/apps/2.2.0.0.1.1.apk\n " }`的情况是有基础headers和`api-key` 怀疑是Pica服务器某种过时的更新检测机制
而再加上`signature`header的话 服务器就只返回200的`code`没有`data`字段.

**Comment by AnkiKong** [comment]
参考go实现，修改你的相关实现，这只能说你哪里写错了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月24日(星期四) 下午4:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AnkiKong/picacomic] 请求用户数据时返回异常错误信息 (#13)





 
看了request.go 和 session.go 关于header构建的内容
 
 
 并且做了修改
 
 
但是依然出错, 错误信息换成了unauthorized
 
另外,出现
 { "code": 400, "error": "必須更新！", "message": "--", "detail": "\n你必須更新才能繼續使用嗶咔漫畫。\n請到官網下載最新更新，\n官網： https://www.picacomic.com\n\n如果不能打開官網請透過以下連結直接下載\nhttps://download.wikawika.xyz/apps/2.2.0.0.1.1.apk\n " }的情况是有基础headers和api-key 怀疑是Pica服务器某种过时的更新检测机制
 而再加上signatureheader的话 服务器就只返回200的code没有data字段.

**Comment by NekoRectifier** [comment]
> 参考go实现，修改你的相关实现，这只能说你哪里写错了
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人: ***@***.***&gt;; 
> 发送时间: 2021年6月24日(星期四) 下午4:56
> 收件人: ***@***.***&gt;; 
> 抄送: ***@***.***&gt;; ***@***.***&gt;; 
> 主题: Re: [AnkiKong/picacomic] 请求用户数据时返回异常错误信息 (#13)
> 
> 
> 
> 
> 
>  
> 看了request.go 和 session.go 关于header构建的内容
>  
>  
>  并且做了修改
>  
>  
> 但是依然出错, 错误信息换成了unauthorized
>  
> 另外,出现
>  { "code": 400, "error": "必須更新！", "message": "--", "detail": "\n你必須更新才能繼續使用嗶咔漫畫。\n請到官網下載最新更新，\n官網： https://www.picacomic.com\n\n如果不能打開官網請透過以下連結直接下載\nhttps://download.wikawika.xyz/apps/2.2.0.0.1.1.apk\n " }的情况是有基础headers和api-key 怀疑是Pica服务器某种过时的更新检测机制
>  而再加上signatureheader的话 服务器就只返回200的code没有data字段.
>  
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

行吧 我再看看
