### ISSUE TITLE
文档的一个小错误

### ISSUE THREAD

**Issue by HomeArchbishop** [AnkiKong/picacomic#15]
https://github.com/AnkiKong/picacomic/blob/1116d4552bdfbf8e7fa7adb2fa1e2d5c50ffecb9/README.md#L271

此行的`{epsId}`更好地表述是`{epsOrder}`，也就是number而不是一长串字符id。

当然这是个无关紧要的事，不过不看py源码容易被误导。

*Thanks in advance.*

**Comment by AnkiKong** [comment]
有标记
https://github.com/AnkiKong/picacomic/blob/master/README.md?plain=1#L254
