### ISSUE TITLE
尝试登陆时报错

### ISSUE THREAD

**Issue by chenmaster05** [AnkiKong/picacomic#3]
```
{
  "code": 400,
  "error": "發現重大版本更新",
  "message": "--",
  "detail": "由於服務器君的問題，因此要強制更新一次。\n\n下載連結：\nhttps://app.wakamoment.tk/apps/2.2.1.2.3.3.apk\nhttps://download.wikawika.xyz/apps/2.2.1.2.3.3.apk\nhttp://www.cnpicacomic.com\nhttps://www.picacomic.com"
}
```

**Comment by MissGoing** [comment]
老哥知道hmac是什么东西吗

**Comment by AnkiKong** [comment]
> ```
> {
>   "code": 400,
>   "error": "發現重大版本更新",
>   "message": "--",
>   "detail": "由於服務器君的問題，因此要強制更新一次。\n\n下載連結：\nhttps://app.wakamoment.tk/apps/2.2.1.2.3.3.apk\nhttps://download.wikawika.xyz/apps/2.2.1.2.3.3.apk\nhttp://www.cnpicacomic.com\nhttps://www.picacomic.com"
> }
> ```

你是怎么写的，去年10月更新的应该还能用的

**Comment by loopcut** [comment]
readme里面的代码是C语言么。。能统一成python么。。生成令牌报错了

**Comment by AnkiKong** [comment]
> readme里面的代码是C语言么。。能统一成python么。。生成令牌报错了

https://github.com/AnkiKong/picacomic/blob/master/pica/pic2.py#L109

**Comment by loopcut** [comment]
登录OK了，也能获取到token了，但是访问其他接口返回值都是{
  "code": 401,
  "error": "1005",
  "message": "unauthorized"
}，请问下现在接口还通么 @AnkiKong

**Comment by AnkiKong** [comment]
> 登录OK了，也能获取到token了，但是访问其他接口返回值都是{
> "code": 401,
> "error": "1005",
> "message": "unauthorized"
> }，请问下现在接口还通么 @AnkiKong

可以的，你发代码看看？

**Comment by MissGoing** [comment]
老哥，为何我的结果都是{"code":200,"message":"success"}，连个data都没

**Comment by XieYuDeGitHub** [comment]
问一下 老哥你知道如何调用哔咔的图片吗

**Comment by AnkiKong** [comment]
> 问一下 老哥你知道如何调用哔咔的图片吗

关于图片链接，由fileServer + "/static/" + path构成
如"https://storage1.picacomic.com/static/653cc9e0-1548-4cc3-bba0-d6e2e1bd9c18.jpg"

**Comment by XieYuDeGitHub** [comment]
谢谢 我去试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AnkiKong/picacomic"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 下午3:11
收件人:&nbsp;"AnkiKong/picacomic"<picacomic@noreply.github.com&gt;;
抄送:&nbsp;"神"<1972664191@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [AnkiKong/picacomic] 尝试登陆时报错 (#3)





  
问一下 老哥你知道如何调用哔咔的图片吗
  
关于图片链接，由fileServer + "/static/" + path构成
 如"https://storage1.picacomic.com/static/653cc9e0-1548-4cc3-bba0-d6e2e1bd9c18.jpg"

**Comment by XieYuDeGitHub** [comment]
我想获取 主目录分区的图片该如何呢 请求是get还是post  是否要带authorization呢

**Comment by XieYuDeGitHub** [comment]
第一次用github 不会回复

**Comment by XieYuDeGitHub** [comment]
老哥 我已经成功的获取到主目录分区图片了 感谢

**Comment by XieYuDeGitHub** [comment]
> 老哥，为何我的结果都是{"code":200,"message":"success"}，连个data都没

这个问题解决了吗 我也卡在这了

**Comment by MissGoing** [comment]
> > 老哥，为何我的结果都是{"code":200,"message":"success"}，连个data都没
> 
> 这个问题解决了吗 我也卡在这了

要指明content-type

**Comment by MissGoing** [comment]
> > 老哥，为何我的结果都是{"code":200,"message":"success"}，连个data都没
> 
> 这个问题解决了吗 我也卡在这了

看其他的iis，他们有说到这个问题

**Comment by AnkiKong** [comment]
> > > 老哥，为何我的结果都是{"code":200,"message":"success"}，连个data都没
> > 
> > 
> > 这个问题解决了吗 我也卡在这了
> 
> 要指明content-type

一般来说，content-type 是库会自动带的，如果库没有带上，那就得自己加了

**Comment by XieYuDeGitHub** [comment]
> > > > 老哥，为何我的结果都是{"code":200,"message":"success"}，连个data都没
> > > 
> > > 
> > > 这个问题解决了吗 我也卡在这了
> > 
> > 
> > 要指明content-type
> 
> 一般来说，content-type 是库会自动带的，如果库没有带上，那就得自己加了

我已经带了 但还是报错

**Comment by XieYuDeGitHub** [comment]
> > > > 老哥，为何我的结果都是{"code":200,"message":"success"}，连个data都没
> > > 
> > > 
> > > 这个问题解决了吗 我也卡在这了
> > 
> > 
> > 要指明content-type
> 
> 一般来说，content-type 是库会自动带的，如果库没有带上，那就得自己加了

我已经带上了 但响应里没有token

**Comment by XieYuDeGitHub** [comment]
![Uploading image.png…]()

**Comment by MissGoing** [comment]
> > > > > 老哥，为何我的结果都是{"code":200,"message":"success"}，连个data都没
> > > > 
> > > > 
> > > > 这个问题解决了吗 我也卡在这了
> > > 
> > > 
> > > 要指明content-type
> > 
> > 
> > 一般来说，content-type 是库会自动带的，如果库没有带上，那就得自己加了
> 
> 我已经带上了 但响应里没有token
不清楚了，不然就是get和post搞错了

**Comment by AnkiKong** [comment]
> > > > > 老哥，为何我的结果都是{"code":200,"message":"success"}，连个data都没
> > > > 
> > > > 
> > > > 这个问题解决了吗 我也卡在这了
> > > 
> > > 
> > > 要指明content-type
> > 
> > 
> > 一般来说，content-type 是库会自动带的，如果库没有带上，那就得自己加了
> 
> 我已经带上了 但响应里没有token

贴代码

**Comment by XieYuDeGitHub** [comment]
> > > > > > 老哥，为何我的结果都是{"code":200,"message":"success"}，连个data都没
> > > > > 
> > > > > 
> > > > > 这个问题解决了吗 我也卡在这了
> > > > 
> > > > 
> > > > 要指明content-type
> > > 
> > > 
> > > 一般来说，content-type 是库会自动带的，如果库没有带上，那就得自己加了
> > 
> > 
> > 我已经带上了 但响应里没有token
> 
> 贴代码

弄好了 Signature计算方法写错了 谢谢老哥
