### ISSUE TITLE
哔咔得错误信息 {"code":400,"error":"1023","message":"too many requests"}

### ISSUE THREAD

**Issue by XieYuDeGitHub** [AnkiKong/picacomic#7]
错误信息说得 too many requests 是什么导致得呢 我想知道原因

**Comment by XieYuDeGitHub** [comment]
> 错误信息说得 too many requests 是什么导致得呢 我想知道原因

找到错误信息了  传了json参数 却没设置 Content-Type头值为application/json; charset=UTF-8

**Comment by dylanliuu** [comment]
> > 错误信息说得 too many requests 是什么导致得呢 我想知道原因
> 
> 找到错误信息了 传了json参数 却没设置 Content-Type头值为application/json; charset=UTF-8

你好，我这边也是这个错误，但我有在Post请求中设置 Content-Type ，但还是如此

**Comment by XieYuDeGitHub** [comment]
> > > 错误信息说得 too many requests 是什么导致得呢 我想知道原因
> > 
> > 
> > 找到错误信息了 传了json参数 却没设置 Content-Type头值为application/json; charset=UTF-8
> 
> 你好，我这边也是这个错误，但我有在Post请求中设置 Content-Type ，但还是如此

方便的话 加我QQ 1972664191 我帮你看看 (我是个菜鸟)
